/**
 * render.ts — Markdown → print-ready HTML (reused from AOP Builder, extended for BOS)
 */

export function buildModuleHTML(
  markdown: string,
  companyName: string,
  moduleTitle: string,
  version = 'v1'
): string {
  const body = mdToHtml(markdown);
  const title = `${companyName} — ${moduleTitle}`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${esc(title)}</title>
  <style>
    *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
    body{font-family:Georgia,'Times New Roman',serif;font-size:10.5pt;line-height:1.65;color:#1a1a2e;background:#fff}
    .wrap{max-width:210mm;margin:0 auto;padding:18mm 16mm 22mm 16mm}
    h1{font-size:20pt;font-weight:700;color:#0f172a;margin:0 0 8pt;line-height:1.2}
    h2{font-size:14pt;font-weight:700;color:#1e3a5f;border-bottom:2px solid #4f46e5;padding-bottom:3pt;margin:18pt 0 8pt}
    h3{font-size:11.5pt;font-weight:700;color:#312e81;margin:12pt 0 5pt}
    h4{font-size:10.5pt;font-weight:600;color:#374151;margin:8pt 0 3pt}
    p{margin:0 0 7pt;orphans:3;widows:3}
    strong{font-weight:700} em{font-style:italic}
    code{font-family:'Courier New',monospace;font-size:9pt;background:#f1f5f9;padding:1pt 4pt;border-radius:2pt}
    table{width:100%;border-collapse:collapse;margin:8pt 0 12pt;font-size:9pt;page-break-inside:avoid}
    th{background:#312e81;color:#fff;font-weight:600;padding:4pt 7pt;text-align:left;border:1px solid #312e81}
    td{padding:3pt 7pt;border:1px solid #cbd5e1;vertical-align:top}
    tr:nth-child(even) td{background:#f8fafc}
    ul,ol{margin:4pt 0 8pt 16pt} li{margin-bottom:2pt}
    blockquote{border-left:4pt solid #4f46e5;padding:3pt 10pt;color:#475569;font-style:italic;margin:8pt 0;background:#eef2ff}
    hr{border:none;border-top:1px solid #e2e8f0;margin:14pt 0}
    .header-bar{background:#1e1b4b;color:#fff;padding:6pt 16mm;font-family:system-ui,sans-serif;font-size:9pt;display:flex;justify-content:space-between}
    .footer-bar{text-align:center;font-family:system-ui,sans-serif;font-size:8pt;color:#94a3b8;padding:8pt 0;border-top:1px solid #e2e8f0;margin-top:20pt}
    .print-btn{position:fixed;top:0;left:0;right:0;background:#312e81;color:#fff;padding:6px 20px;display:flex;gap:12px;align-items:center;font-family:system-ui,sans-serif;font-size:12px;z-index:999}
    .print-btn button{background:#4f46e5;color:#fff;border:none;padding:5px 14px;border-radius:4px;cursor:pointer;font-size:12px;font-weight:600}
    @media print{
      @page{size:A4;margin:18mm 15mm 20mm 15mm}
      .print-btn,.no-print{display:none!important}
      .wrap{padding:0;margin-top:0}
      h2{page-break-before:auto;page-break-after:avoid}
      table{page-break-inside:avoid}
    }
    @media screen{body{background:#f1f5f9}.wrap{background:#fff;box-shadow:0 4px 20px rgba(0,0,0,.1);margin:40px auto;border-radius:4px}}
  </style>
</head>
<body>
  <div class="print-btn no-print">
    <span>📋 BOS Builder — ${esc(moduleTitle)} (${version})</span>
    <button onclick="window.print()">🖨️ Print / Save PDF</button>
    <button onclick="this.parentElement.style.display='none'" style="background:#475569">Hide</button>
  </div>
  <div class="header-bar no-print">
    <span><strong>${esc(companyName)}</strong></span>
    <span>${esc(moduleTitle)} · ${version} · Confidential</span>
  </div>
  <div class="wrap" style="margin-top:40px">
    ${body}
    <div class="footer-bar">
      ${esc(companyName)} · ${esc(moduleTitle)} · ${version} · Generated by BOS Builder · Confidential
    </div>
  </div>
</body>
</html>`;
}

export function buildMasterPackHTML(
  modules: { title: string; markdown: string }[],
  companyName: string,
  planningYear: string
): string {
  const sections = modules
    .map(m => `<section class="module-section"><div class="module-break"></div>${mdToHtml(m.markdown)}</section>`)
    .join('\n');

  return buildModuleHTML(sections, companyName, `Business Operating System — ${planningYear}`, 'vFinal');
}

// ─── Lightweight MD → HTML converter ─────────────────────────────────────────

export function mdToHtml(md: string): string {
  let html = md;
  html = html.replace(/^######\s(.+)$/gm, '<h6>$1</h6>');
  html = html.replace(/^#####\s(.+)$/gm,  '<h5>$1</h5>');
  html = html.replace(/^####\s(.+)$/gm,   '<h4>$1</h4>');
  html = html.replace(/^###\s(.+)$/gm,    '<h3>$1</h3>');
  html = html.replace(/^##\s(.+)$/gm,     '<h2>$1</h2>');
  html = html.replace(/^#\s(.+)$/gm,      '<h1>$1</h1>');
  html = html.replace(/^---+$/gm,         '<hr>');
  html = html.replace(/\*\*\*(.+?)\*\*\*/g, '<strong><em>$1</em></strong>');
  html = html.replace(/\*\*(.+?)\*\*/g,     '<strong>$1</strong>');
  html = html.replace(/\*(.+?)\*/g,         '<em>$1</em>');
  html = html.replace(/`(.+?)`/g,           '<code>$1</code>');
  html = html.replace(/^> (.+)$/gm,         '<blockquote>$1</blockquote>');
  html = html.replace(/^- \[ \] (.+)$/gm,   '<li><input type="checkbox" disabled> $1</li>');
  html = html.replace(/^- \[x\] (.+)$/gm,   '<li><input type="checkbox" checked disabled> $1</li>');

  // Tables
  html = html.replace(/((?:^\|.+\|\s*\n)+)/gm, (match) => {
    const lines = match.trim().split('\n');
    if (lines.length < 2 || !/^\|[-| :]+\|/.test(lines[1])) return match;
    const parseRow = (line: string, tag: string) =>
      '<tr>' + line.split('|').slice(1,-1).map(c => `<${tag}>${c.trim()}</${tag}>`).join('') + '</tr>';
    return `<div style="overflow-x:auto"><table><thead>${parseRow(lines[0],'th')}</thead><tbody>${lines.slice(2).map(l=>parseRow(l,'td')).join('')}</tbody></table></div>`;
  });

  // Lists
  html = html.replace(/((?:^(?:- |\* ).+\n?)+)/gm, m =>
    `<ul>${m.trim().split('\n').map(l => l.replace(/^(?:- |\* )(.+)$/,'<li>$1</li>')).join('')}</ul>`
  );
  html = html.replace(/((?:^\d+\. .+\n?)+)/gm, m =>
    `<ol>${m.trim().split('\n').map(l => l.replace(/^\d+\. (.+)$/,'<li>$1</li>')).join('')}</ol>`
  );

  // Paragraphs
  html = html.replace(/^(?!<[a-z\/]|$)(.+)$/gm, '<p>$1</p>');
  html = html.replace(/\n{3,}/g, '\n\n');
  return html;
}

function esc(s: string): string {
  return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}
